---
- name: Pure Storage LB example
  hosts: localhost
  gather_facts: yes
  collections:
    - purestorage.flasharray
  vars_files:
    - testdrive_vars.yaml
  vars:
    array_usage: []
  roles:
    - role: lb

  tasks:
    - name: Provisioning {{ use_name }}
      purefa_volume:
        fa_url: "{{ use_url }}"
        api_token: "{{ use_api }}"
        name: lbtest01
        size: 50G
