---
- hosts: localhost
  gather_facts: True
  become: True
  vars:
    epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    epel_repofile_path: "/etc/yum.repos.d/epel.repo"
  tasks:
  - name: Install EPEL repo.
    yum:
      name: "{{ epel_repo_url }}"
      state: present
    when: ansible_os_family == "RedHat"

  - name: Import EPEL GPG key.
    rpm_key:
      key: "{{ epel_repo_gpg_key_url }}"
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install python-pip module on RedHat
    yum:
      name: python-pip
    when: ansible_os_family == "RedHat"

  - name: Install python-pip module on Ubuntu
    apt:
      name: python-pip
    when: ansible_os_family == "Debian"

  - name: Install python-pip module on SuSE
    zypper:
      name: python-pip
    when: ansible_os_family == "Suse"

  - name: Install Pure Storage SDKs
    pip:
      name: ['purestorage', 'purity_fb']
