---
- hosts: localhost
  become: true
  vars:
    Files: []
  tasks:
  - name: Copy file with owner and permisions.
    synchronize:
      src: /etc
      dest: /TestDir

  - name: Find files larger than 100k
    become: true
    find:
      paths: /TestDir/etc
      file_type: directory
      recurse: no
    register: output

  - name: Add files to the list
    no_log: true
    set_fact:
      Files: "{{ Files + [item.path] }}"
    with_items: "{{ output.files }}"

  - debug: var=Files
