- hosts: localhost
  gather_facts: true
  collections:
     - purestorage.flasharray
  tasks:
    - name: Get FlashArray Info
      purefa_info:
          fa_url: 172.16.3.111
          api_token: ff703c77-4db4-5e84-6734-b2d37acce147
    
    - name: Create a volume
      purefa_volume:
          name: ansvol1
          size: 100G
          fa_url: 172.16.3.111
          api_token: ff703c77-4db4-5e84-6734-b2d37acce147

    - name: Create host
      purefa_host:
          name: "{{ ansible_hostname }}"
          protocol: iscsi
          iqn: "{{ ansible_iscsi_iqn }}"
          fa_url: 172.16.3.111
          api_token: ff703c77-4db4-5e84-6734-b2d37acce147
