- name: Clean up the existing Linux config
  hosts: localhost
  gather_facts: true
  collections:
  - purestorage.flasharray
  vars_files:
  - testdrive_vars.yaml
  tasks:

    - name: Get destination array information
      purefa_info:
         gather_subset:
         - network
         - volumes
         fa_url: "{{ fa1_ip }}"
         api_token: "{{ fa1_token }}"
      register: fa1_info

    - set_fact:
        volume_serial: "{{ fa1_info.purefa_info.volumes[orig_volume].serial }}"

    - name: Rename volume linux-lun-01 to boot!
        purefa_volume:
                name: linux-lun-01
                rename: linux-boot-vol
